course_work/app/routes.py
from flask import Blueprint, render_template, send_from_directory, current_app, abort
from course_work.app.repositories import user_repository
from course_work.app.models import db 
from course_work.app.repositories.route_repository import RouteRepository 
 
bp = Blueprint('main', __name__)


repo = RouteRepository(db)

@bp.route('/')
def index():
    category_cards = repo.get_category_cards()
    return render_template("index.html", category_cards=category_cards)


@bp.route('/product/<int:product_id>')
def product_detail(product_id):
    product = repo.get_product_with_details(product_id)
    return render_template('catalog/product_detail.html', product=product)

course_work/app/templates/catalog/catalog.html
{% extends 'base.html' %}

{% block title %}Каталог{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='catalog.css') }}">
{% endblock %}

{% block content %}
<div class="container-catalog">
    <aside class="filters">
        <h3>Фильтры</h3>
        <form method="get" action="{{ url_for('catalog.catalog') }}">
            <label><b>Цена</b></label>
            <input type="number" name="min_price" placeholder="От" value="{{ min_price or '' }}">
            <input type="number" name="max_price" placeholder="До" value="{{ max_price or '' }}">

            <label><b>Тип</b></label>
            {% for category in categories %}
            <label>
                <input type="checkbox" name="category" value="{{ category.id }}" {% if category.id|string in
                    selected_categories %}checked{% endif %}>
                {{ category.name }}
            </label>
            {% endfor %}

            <label><b>Бренд</b></label>
            {% for brand in brands %}
            <label>
                <input type="checkbox" name="brand" value="{{ brand.id }}" {% if brand.id|string in selected_brands
                    %}checked{% endif %}>
                {{ brand.name }}
            </label>
            {% endfor %}
            <label><b>_______</b></label>
            <label>
                <input type="checkbox" name="available" value="1" {% if available %}checked{% endif %}>
                Только в наличии
            </label>
            <button type="submit">Применить</button>
        </form>
    </aside>


    <main class="catalog">
        <h1>Каталог товаров</h1>
        <div class="products-grid">
            {% for product in products %}
            <div class="product-card">

                <a href="{{ url_for('main.product_detail', product_id=product.id) }}" class="card-link">
                    <div class="card-content">
                        <img src="{{ product.image_url or '/static/default.jpg' }}" alt="{{ product.name }}">
                        <h3>{{ product.name }}</h3>
                        <p>{{ product.category.name }}</p>
                        {% if product.stock_quantity > 0 %}
                        <p><strong>{{ product.price }} ₽</strong></p>
                        {% else %}
                        <p class="not-available-price">Нет в наличии</p>
                        {% endif %}
                    </div>
                </a>

                <form method="post" action="{{ url_for('cart.add_to_cart', product_id=product.id) }}">
                    <button type="submit" class="add-btn" title="Добавить в корзину">+</button>
                </form>

            </div>
            {% endfor %}
        </div>


        <!-- Пагинация -->
        <div class="pagination">
            {% if pagination.has_prev %}
            <a href="{{ url_for('catalog.catalog', page=pagination.prev_num, 
                    category=selected_categories, 
                    brand=selected_brands,
                    min_price=min_price,
                    max_price=max_price,
                    available=available) }}">
                Назад
            </a>
            {% endif %}

            {% for p in pagination.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if p %}
            {% if p == pagination.page %}
            <span class="current">{{ p }}</span>
            {% else %}
            <a href="{{ url_for('catalog.catalog', page=p, 
                    category=selected_categories, 
                    brand=selected_brands,
                    min_price=min_price,
                    max_price=max_price,
                    available=available) }}">
                {{ p }}
            </a>

            {% endif %}
            {% else %}
            <span>...</span>
            {% endif %}
            {% endfor %}

            {% if pagination.has_next %}
            <a href="{{ url_for('catalog.catalog', page=pagination.next_num, 
                    category=selected_categories, 
                    brand=selected_brands,
                    min_price=min_price,
                    max_price=max_price,
                    available=available) }}">
                Вперед
            </a>
            {% endif %}
        </div>

    </main>
</div>
{% endblock %}

course_work/app/templates/catalog/product_detail.html
{% extends 'base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block head%}
<link rel="stylesheet" href="{{ url_for('static', filename='product_detail.css') }}">
{% endblock %}

{% block content %}
<main class="container product-detail-page">
    <div class="product-card">
        <div class="product-image">
            <img src="{{ product.image_url }}" alt="{{ product.name }}">
        </div>

        <div class="product-info">
            <h2>{{ product.name }}</h2>
            <p class="sku">Артикул: {{ product.sku }}</p>

            <p class="price">{{ product.price }} ₽</p>
            {% if product.stock_quantity > 0 %}
            <p class="in-stock">В наличии</p>
            {% else %}
            <p class="not-stock">Нет в наличии</p>
            {% endif %}
            <h4>Основные характеристики:</h4>

            {% if product.guitar_details %}
            <ul class="features">
                <li>Тип: {{ product.guitar_details.type }}</li>
                <li>Количество струн: {{ product.guitar_details.strings_number }}</li>
                <li>Материал корпуса: {{ product.guitar_details.body_material }}</li>
                <li>Материал грифа: {{ product.guitar_details.neck_material }}</li>
                <li>Звукосниматели: {{ product.guitar_details.pickups or 'Нет' }}</li>
            </ul>

            {% elif product.accessory_details %}
            <ul class="features">
                <li>Назначение: {{ product.accessory_details.compatibility }}</li>
                <li>Материал: {{ product.accessory_details.material }}</li>
                <li>Цвет: {{ product.accessory_details.color }}</li>
            </ul>
            {% else %}
            <p>Характеристики недоступны.</p>
            {% endif %}


            <form method="post" action="{{ url_for('cart.add_to_cart', product_id=product.id) }}">
                <div class="quantity-selector">
                    <button type="button" onclick="changeQty(-1)">−</button>
                    <input type="number" name="quantity" id="quantity" value="1" min="1">
                    <button type="button" onclick="changeQty(1)">+</button>
                </div>
                <button type="submit" class="btn-filled">Добавить в корзину</button>
            </form>
        </div>
    </div>

    <div class="product-description">
        <h3>Описание</h3>
        <p>{{ product.description or 'Описание будет добавлено позже.' }}</p>
    </div>
</main>

<script>
    function changeQty(delta) {
        const qtyInput = document.getElementById('quantity');
        let current = parseInt(qtyInput.value);
        if (!isNaN(current)) {
            qtyInput.value = Math.max(1, current + delta);
        }
    }
</script>
{% endblock %}